
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: cart-service-ingress
 annotations:
   kubernetes.io/ingress.class: kong
   konghq.com/strip-path: "true"
spec:
 rules:
 - http:
     paths:
     - path: /cart
       pathType: Prefix
       backend:
         service:
           name: cart-service
           port:
             number: 32601

---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: twelveperminutes
config:
  minute: 12
  policy: local
plugin: rate-limiting